// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2qIog4Awjgj6P0spMekDaDT0yvBPsDQE',
    appId: '1:1019518998128:web:b07d9d41e4165a921a86b5',
    messagingSenderId: '1019518998128',
    projectId: 'chat-app-7e5e8',
    authDomain: 'chat-app-7e5e8.firebaseapp.com',
    storageBucket: 'chat-app-7e5e8.firebasestorage.app',
    measurementId: 'G-634VLHVC4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8XmvSXa2ghJhz-k1YCmzjM01OIygzqOU',
    appId: '1:1019518998128:android:b8aa46e7122b8d871a86b5',
    messagingSenderId: '1019518998128',
    projectId: 'chat-app-7e5e8',
    storageBucket: 'chat-app-7e5e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC72qvk8TyNta5HnTqKdg1i4u9aKhxmGpw',
    appId: '1:1019518998128:ios:3470ab8d21b6eb701a86b5',
    messagingSenderId: '1019518998128',
    projectId: 'chat-app-7e5e8',
    storageBucket: 'chat-app-7e5e8.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
}